### PR TITLE
Form validation

### PR DESCRIPTION
**Pull request by stino-x**
message cannot be inputed in capital letters

### CODE REVIEW

**Review by EricMbouwe — APPROVED** [review]
Hi @stino-x, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- Validation ✔
- No linter errors ✔

## Optional suggestions ☂
- I would suggest changing the error message to something related to validation and not to the case of the password

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by 1GORDON — COMMENTED** [review]
##
## Hi @stino-x ✋

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [ ]  You have submitted a PR which is already approved and closed. Kindly consider submitting a correct PR whenever you are ready.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by stino-x** [comment]
@1GORDON hello this is a project that required just one of us to do in our repo and it was my partners , he closed the pull request because it was approved

**Review by Nemwel-Boniface — COMMENTED** [review]
## Hello @stino-x   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request and inspected your complaint about @1GORDON . His review was very ok and inline with the rules that are given.

Just as he had mentioned to you:

1. When repeating a week/ module, for solo projects which were already approved, you can get an approval immediately.
2. When repeating a week/ module, for group/ pair programming projects, **you are required to open a new PR and ensure that you work with your new pair programming partners in your new collaborating week.**.

**Also note the following:**
1. Second opinion requests that are submitted on a Sunday will not be processed until Monday and requesting for a second opinion is better done early on a weekday (preferred for a quicker response).
2. I would like to urge you to be keen when selecting the reviewer's name correctly so that you do not end up selecting the wrong reviewer in your second opinion. In this case, the reviewer you selected (Toluwase Oluwasegun Ajise) did not make a review in this PR. 

Therefore for this situation, you were supposed to open a new PR and work with your new partner(s) in your new collaborative week and request for a review from a new pull request. Find attached the work and submission mode from the validate contact form [project guidelines](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/9_validate_form.md).

Screenshot from 2023-04-17 11-03-40



In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

**Pull request closed without merging**
