### PR TITLE
Mobile menu

### PR DESCRIPTION
**Pull request by stino-x**
I added a navigation menu with the help of javascript

### CODE REVIEW

**Review by algerina — APPROVED** [review]
Hi @stino-x ,

Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:



 
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

**Review by emmiiorji — COMMENTED** [review]
Hi @stino-x, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>

</div>

You have submitted an already approved pull request. While it's understandable that this is repeated project and should receive straightway approval if it was a solo project, it is required to be completed by pair programming.

Kindly complete the project with your new teammate(s).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by stino-x** [comment]
hi @emmiiorji when i was repeating they said i could resubmit old work i had already done i did this with my partner then that and i passed it, also  my partner and i worked together on his projects as well (if not he wouldnt have been able to pass) it was stated in the letter they sent to me i dont see the issue here

**Comment by emmiiorji** [comment]
Hi @stino-x

I totally understand the point you've raised. When repeating a block, you could resubmit your approved pull requests and receive an immediate approval as long as they're solo projects. For pair programming milestones as this, you need to complete them with your new partner.

However, if you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by Nemwel-Boniface — COMMENTED** [review]
## Hello @stino-x   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request and inspected your complaint about @emmiiorji. His review was very ok and inline with the rules that are given.

Just as he had mentioned to you:

1. When repeating a week/ module, for solo projects which were already approved, you can get an approval immediately.
2. When repeating a week/ module, for group/ pair programming projects, **you are required to open a new PR and ensure that you work with your new pair programming partners in your new collaborating week.**.

**Also note the following:**
1. Second opinion requests that are submitted on a Sunday will not be processed until Monday and requesting for a second opinion is better done early on a weekday (preferred for a quicker response).

Therefore for this situation, you were supposed to open a new PR and work with your new partner(s) in your new collaborative week and request for a review from a new pull request. Find attached the work and submission mode from the mobile menu [project guidelines](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md).

image


In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

**Pull request merged**
